[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"

# Try to disable Railway's default security headers
[experimental]
disableSecurityHeaders = true
