[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"

# Disable Railway's default security headers so we can set our own
[security]
disableDefaultHeaders = true
